apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: phone-md-hp-app
  labels:
    app: phone-md-hp-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/O-Hahn/phone-motiondetection-app
      ref: v3-harrypotter
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: phone-md-hp-app:latest